### ISSUE TITLE
Engineering Requirement 3 Plausibility (Neil, I ran out of time, I will continue this soon)

### ISSUE THREAD

**Issue by djangodemetri** [glazet/QuadEVCharger#27]
ER3: Must be capable of switching current nominally at 208VAC

Problems:
We need to make sure we can actually achieve this engineering requirement 
1. We need door access to the room with plug (not time pertinent)
2. Find wire that can handle 208VAC (not hard). This needs to consider amperage as well. (not time pertinent)
3. Double check that we have equipment that can read 208VAC. If not, we need to step the voltage down. (pertinent)

Solutions:
1. Door access is easy but needs to be listed
2. AWG is the United States standard for wire sizing. There are charts for all of these specs.
3. Do any professors/Shahram have devices that can read 208VAC? If not, we need to consider alternatives, (voltage devices)

Implementation:
3. Actually test this. Does it work? If it doesn't work, are you confident the solution can be found or are you guessing?

Future:
Think of anymore roadblocks, **THE IMPORTANCE OF THIS CANNOT BE OVERSTATED**

**Comment by neilh10** [comment]
@djangodemetri  - you are getting way too complicated, and lacking focus on the engineering challenge.   

Ask Shahram if he has approx 208 (possibly 220) VAC on a socket that you can plug in the system to test its "control function"

Specify all wires to be at a higher voltage.

My suggestion is that you do this as the very LAST test. 
If it doesn't work and you blow up something as its not specified correctly it won't block other tests
