### ISSUE TITLE
Simple Product Description

### ISSUE THREAD

**Issue by neilh10** [glazet/QuadEVCharger#4]
Issue can be used as tracking items. I'm generating a few here to be tracked and discussed

What is a simple product description?. In keeping it simple, the exact words may be re-defined as there is more understanding of the potential customers

**Comment by CalvinJDP** [comment]
Our team, Kilowatt Kings, is currently working on the design of a Smart Quad Electric Vehicle Charger. We have three primary objectives we aim to address. Our first objective is to address the new 2023 CalGreen requirement, which mandates one EV charger per four parking spaces. Our second objective is to efficiently provide charging for a 1:4 ratio of cars per charging station. Out third objective is to ensure that each car receives a charge sufficient for an estimated 30-mile commute, considering the average commute distance in California. Our approach to achieve these objectives involves designing a single-unit EV charger capable of accommodating four cars simultaneously. Each car will receive approximately 30 minutes of charge time before the system cycles to the next vehicle.

**Comment by glazet** [comment]
An even more simple version:
Our team, the Kilowatt Kings, are designing an EV charger that can charge up to four vehicles from a single charging station and will meet upcoming CALGreen regulations. The charger will provide enough charge to the vehicle to make a 30-mile commute. When multiple vehicles are plugged in, the station will decide which vehicle gets charge and for how long.
