### ISSUE TITLE
What questions should be asked of potential customers while researching Quad EV Chargee

### ISSUE THREAD

**Issue by neilh10** [glazet/QuadEVCharger#6]
Neil email : 3) and then what questions for potential customers when you meet with them.
Focused question on the potential customer pain more appropriate than the
engineering of tell us your specification for our product.

Bob Salter email : 5.      In my opinion your interview questions should be focused on
discovering pain points/wants/needs. The questions will likely be different
for each type of customer that you interview. 

@glazet provided a brain storming first pass - can you filter them through the above lens and post here.

**Comment by CalvinJDP** [comment]
We have revisited the interview questions, I have posted them below. We are actively adding questions as we learn more about EV chargers.

 1) Are you familiar with the new upcoming CalGreen requirements for EV chargers?
 2) When designing EVSE, do you have any environmental concerns such as 
     weatherproofing or site development?
 3) What are your concerns, if any, about electrical infrastructure in a given complex? 
 4) *Site Owner* Do you currently have the electrical infrastructure to install EV chargers? 
5) How do you envision scaling up/adding EV charging infrastructure to accommodate the growth of EVs?
 6) What challenges do you encounter during peak charging hours?
 7) Have you experienced any issues or challenges with existing EV chargers that you would like addressed in a new design?
 8) What is your preferred charging station/charging connector type?
 9) Are you open to providing feedback during the charger development process?
10) What do you consider crucial to ensure that EV charging stations are accessible for residents and customers?
11) How much space do you typically have to integrate new EV charging stations? Do you have a lot of space to work with or not a lot?
12) *If they do not have EV charging stations*Are you considering whether to make your EV charging stations available to the public or restrict their use solely to your tenants?
13) Given the potential cost of upgrading and installing these stations, are you planning to offer usage for free, include their usage cost within the rent, or charge users directly for their use?
