### ISSUE TITLE
What specifications

### ISSUE THREAD

**Issue by neilh10** [glazet/QuadEVCharger#7]
What specifications does an EV Charger need to meet.  Provide a link or reference to the specification - this is likely to become a marketing specification.

**Comment by djangodemetri** [comment]
[NEC 625 (Page 25)](https://www.nrel.gov/docs/fy21osti/78085.pdf) specifies installation of EVSE, 
     Circuit breakers sized for 125% of load (which would be 50A for us)
     8AWG for cable
     Length less than 25 feet
     No back-feeding from EV when grid loses power

[ISO 15118's Plug and Charge](https://en.wikipedia.org/wiki/ISO_15118) controls identification and authentication over IP

[IEC 61851-1](https://webstore.iec.ch/publication/33644) defines duty cycle values Control Pilot (CP)

[Open Charge Point Interface (OCPI)](https://www.ampcontrol.io/post/what-is-ocpi-and-why-is-it-important-for-ev-operators) allows cross company payment/charging

[Open Charge Point Protocol (OCPP)](https://en.wikipedia.org/wiki/Open_Charge_Point_Protocol) is protocol between EVSE and network 

[IEC Mode 3](https://www.allaboutcircuits.com/technical-articles/four-ev-charging-modes-iec61851-standard/) means permanent cord set

[IC-CPD](https://www.aptiv.com/docs/default-source/user-manual/english-user-manual-ic-cpd.pdf?sfvrsn=acac163e_2) provides additional circuit breaker and ground monitoring

[NEMA 14-50R](https://calgreenenergyservices.com/2022/08/24/2022-calgreen-tier-1-and-2-ev-requirements/) is receptacle for EVSE

[HOA and EVSE Interactions](https://california.public.law/codes/ca_civ_code_section_4745)
