### ISSUE TITLE
List all EV charger products/manufactures 

### ISSUE THREAD

**Issue by neilh10** [glazet/QuadEVCharger#9]
List the EV Chargers with a reference to the specification sheet - how many do they support

**Comment by CalvinJDP** [comment]
Here is a lit of some EV Chargers specifically Level 2 chargers

- [ChargePoint](https://www.chargepoint.com/drivers/home/flex-promo?utm_source=google&utm_medium=cpc&utm_campaign=IV_G_NB_S&utm_term=home%20charging%20point&utm_matchtype=p&ad_content=646558734667&gclid=CjwKCAjw6p-oBhAYEiwAgg2PgiyAwJnodi8eLQXd84hlYmDq4hRcEUl_aqgS-MnL2FQUcVz35BpCshoCZlYQAvD_BwE)
50 Amps, NEMA plug, Single Port Charger

- [Electrify America](https://www.electrifyhome.com/homestation)
40 amps, NEMA plug, Single Port Charger

- [Grizzl-E Duo](https://grizzl-e.com/product/usa/duo/grizzl-e-duo/)
40 amps, NEMA plug, Dual port Charger (Splits current)

- [REV+ Dual Port](https://www.rplusev.com/online-store/REV-Dual-Port-Level-2-Electric-Vehicle-Smart-Charger-50-Amps-WiFi-Bluetooth-UL-Listed-Mobile-App-Integration-p101982974)
50 Amps, J1772, Dual Port Charger

- [EvoCharge](https://evocharge.com/product/evocharge-40-amp-ievse-home/?utm_source=Google%20Shopping&utm_campaign=Google%20Shopping&utm_medium=cpc&utm_term=9970&gclid=CjwKCAjw6p-oBhAYEiwAgg2PgqNF_jtciK4fLB-5hCec-tEDNB7JGpiHxDAIJinuKXRSvVh6MmLThxoCViAQAvD_BwE)
40 Amps, J1772, Dual Charger

- [ClipperCreek](https://enphase.com/store/ev-chargers/residential-ev-chargers/clippercreek-hcs-d50r-dual-ev-charger-hardwired)
32 or 40 Amps, J1772, Dual Port Charger (Split current)

-[BOSCH](https://boschevsolutions.com/charging-stations/ev800-series-bollards)
32 amps, J1172, Dual  Port Charger
